version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: pirategame_websvr1
        ports:
            - "8000:8000"
        command: /usr/local/bin/gunicorn -w 1 -k gevent --graceful-timeout 3600000 --timeout 999999999 --bind 0.0.0.0:8000 flask_main:app
        volumes:
            - pirategame_webserver:/application

    database:
        image: mariadb:latest
        hostname: pirategame_dbsvr1
        environment:
            MARIADB_ROOT_PASSWORD: local-only
            MARIADB_USER: pirategame_python
            MARIADB_PASSWORD: local-only
            MARIADB_DATABASE: pirategame
        ports:
            - "3306:3306"
        volumes:
            - pirategame_db:/var/lib/mysql

    gameserver:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: pirategame_gamesvr1
        ports:
            - "8001:5000"
        command: python3 /application/gameserver.py
        volumes:
            - pirategame_gameserver:/application
volumes:
    pirategame_db: {}
    pirategame_webserver: {}
    pirategame_gameserver: {}