# Generated by Django 4.0.6 on 2022-08-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=20)),
                ('game_settings', models.JSONField()),
                ('game_square_order', models.CharField(max_length=1000)),
                ('game_current_round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_nickname', models.CharField(max_length=20)),
                ('player_is_host', models.BooleanField(default=False)),
                ('player_money', models.JSONField(default=master.models.Player.money_default)),
                ('player_retaliations', models.JSONField(default=master.models.Player.retals_default)),
                ('player_grid', models.CharField(max_length=1000)),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.game')),
            ],
        ),
    ]
