# Generated by Django 4.0.6 on 2022-07-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_is_host', models.BooleanField(default=False)),
                ('user_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.game')),
            ],
        ),
    ]
