# Generated by Django 4.0.6 on 2022-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_game_settings_game_game_gameplay_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_nickname',
            field=models.CharField(max_length=30),
        ),
    ]
