# Generated by Django 4.0.6 on 2022-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_player_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_nickname',
            field=models.CharField(max_length=15),
        ),
    ]
