# Generated by Django 4.0.6 on 2022-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_game_game_title_alter_player_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_grid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
