# Generated by Django 4.0.6 on 2022-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_player_player_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_nickname',
            field=models.CharField(blank=True, default='projector', max_length=15),
        ),
    ]
